# Generated by Django 5.2.10 on 2026-02-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guthi', '0004_futsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guthi.futsal')),
            ],
        ),
    ]
