# Generated by Django 5.2.10 on 2026-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guthi', '0009_remove_profile_image_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
    ]
