# Generated by Django 5.2.10 on 2026-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guthi', '0010_profile_full_name_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='price_per_hour',
            field=models.IntegerField(default=1000),
        ),
    ]
