# Generated by Django 5.2.10 on 2026-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guthi', '0011_futsal_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futsal',
            name='peak_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='peak_price',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='futsal',
            name='peak_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='weekend_price',
            field=models.IntegerField(default=1200),
        ),
    ]
